language: python

python:
  - "3.7"
  
install:
  - pip install .[docs]

script:
  - python -m unittest
  
after_success:
  - cd docs && make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/build/html
  committer-from-gh: true
  on:
    branch: master