language: python

python:
  - 3.7
  
before_install:
    - sudo apt-get install pandoc

install:
    - pip install coveralls
    - pip install .[docs]

script:
    - coverage run setup.py test
  
after_success:
    - coveralls
    - make -C docs html

deploy:
    provider: pages
    cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/build/html
    on:
        branch: master